// frontend/src/components/monitor/form/ExtractionEditor.tsx
import { useRef, useState } from 'react'
import { previewScan } from '@/api/monitors'
import type { ScanContainer } from '@/api/types'
import type { ExtractionField, SourceMode, MonitorFormState } from '@/lib/monitorForm'
import './ExtractionEditor.css'

interface ExtractionEditorProps {
  value: MonitorFormState['extraction']
  url?: string
  advanced?: boolean
  onChange: (value: MonitorFormState['extraction']) => void
}

export default function ExtractionEditor({ value, url = '', advanced = false, onChange }: ExtractionEditorProps) {
  const [scanning, setScanning] = useState(false)
  const [scanResult, setScanResult] = useState<{ containers?: ScanContainer[] } | null>(null)
  const [scanned, setScanned] = useState(false)
  const [scanError, setScanError] = useState<string | null>(null)
  const [selectedIndex, setSelectedIndex] = useState<number | null>(null)

  // 唯一候选会在 await 之后被自动套用，从 ref 取最新值，避免覆盖扫描期间的用户编辑
  const valueRef = useRef(value)
  valueRef.current = value

  async function handleScan() {
    if (scanning || !url) return
    setScanning(true)
    setScanned(false)
    setScanError(null)
    setSelectedIndex(null)
    try {
      const res = await previewScan({ url: url.trim() })
      if (res.code === 0 && res.data) {
        if (res.data.containers?.length === 1) {
          applyCandidate(res.data.containers[0])
          setScanning(false)
          return
        }
        setScanResult(res.data)
      } else {
        setScanError(res.message || '扫描失败')
      }
    } catch (e) {
      setScanError(e instanceof Error ? e.message : '扫描失败')
    }
    setScanned(true)
    setScanning(false)
  }

  function applyCandidate(container: ScanContainer) {
    const config = container.config || {}
    const fields: ExtractionField[] = (config.fields || []).map((f) => ({
      name: f.name || '',
      selector: f.selector || '',
      type: f.type || 'text',
      attr: f.attr || '',
      transform: f.transform || '',
    }))
    const extracted: MonitorFormState['extraction'] = {
      ...valueRef.current,
      containerSelector: config.container || container.container_css || '',
      itemSelector: config.item || container.item_css || '',
    }
    if (config.fetch_config) {
      extracted.sourceMode = (config.fetch_config.mode as SourceMode) || 'html'
      extracted.sourceUrl = config.fetch_config.url || ''
      extracted.itemsPath = config.fetch_config.items_path || ''
      extracted.filterPath = config.fetch_config.filter_path || ''
      extracted.filterEquals = config.fetch_config.filter_equals ?? ''
      extracted.sourceHeaders = config.fetch_config.headers || {}
    } else {
      extracted.sourceMode = 'html'
      extracted.sourceUrl = ''
      extracted.itemsPath = ''
      extracted.filterPath = ''
      extracted.filterEquals = ''
      extracted.sourceHeaders = {}
    }
    if (fields.length > 0) extracted.fields = fields
    onChange(extracted)
    setScanned(false)
    setScanResult(null)
  }

  function update<K extends keyof MonitorFormState['extraction']>(key: K, v: MonitorFormState['extraction'][K]) {
    onChange({ ...value, [key]: v })
  }

  function updateSourceMode(mode: string) {
    const next = { ...value, sourceMode: mode as SourceMode }
    if (mode === 'html') {
      next.sourceUrl = ''
      next.itemsPath = ''
      next.filterPath = ''
      next.filterEquals = ''
      next.sourceHeaders = {}
    }
    onChange(next)
  }

  function updateSourceHeader(name: string, v: string) {
    const headers = { ...(value.sourceHeaders || {}) }
    if (v.trim()) headers[name] = v
    else delete headers[name]
    onChange({ ...value, sourceHeaders: headers })
  }

  function updateField(index: number, key: keyof ExtractionField, v: string) {
    const fields = [...value.fields]
    fields[index] = { ...fields[index], [key]: v }
    onChange({ ...value, fields })
  }

  function addField() {
    const fields = [...value.fields, { name: '', selector: '', type: 'text', attr: '', transform: '' }]
    onChange({ ...value, fields })
  }

  function removeField(index: number) {
    const fields = [...value.fields]
    fields.splice(index, 1)
    onChange({ ...value, fields })
  }

  if (advanced) {
    return (
      <div className="advanced-panel-section extraction-editor">
        <h3>网页提取规则</h3>
        <p className="advanced-section-desc">仅在自动识别不准确时修改这些技术选项。</p>
        <div className="form-group">
          <label>数据源</label>
          <select value={value.sourceMode || 'html'} onChange={(e) => updateSourceMode(e.target.value)} className="form-input">
            <option value="html">网页 HTML</option>
            <option value="api_json">公开 JSON API</option>
          </select>
        </div>

        {value.sourceMode === 'api_json' && (
          <>
            <div className="source-grid">
              <div className="form-group source-url">
                <label>JSON API URL</label>
                <input
                  value={value.sourceUrl}
                  onChange={(e) => update('sourceUrl', e.target.value)}
                  className="form-input"
                  placeholder="https://example.com/api/products"
                />
              </div>
              <div className="form-group">
                <label>列表路径</label>
                <input value={value.itemsPath} onChange={(e) => update('itemsPath', e.target.value)} className="form-input" placeholder="data.items" />
              </div>
              <div className="form-group">
                <label>过滤字段（可选）</label>
                <input value={value.filterPath} onChange={(e) => update('filterPath', e.target.value)} className="form-input" placeholder="is_selling" />
              </div>
              <div className="form-group">
                <label>过滤值</label>
                <input value={value.filterEquals} onChange={(e) => update('filterEquals', e.target.value)} className="form-input" placeholder="true" />
              </div>
            </div>
            <div className="header-grid">
              <div className="form-group">
                <label>Accept</label>
                <input
                  value={value.sourceHeaders?.Accept || ''}
                  onChange={(e) => updateSourceHeader('Accept', e.target.value)}
                  className="form-input"
                  placeholder="application/json"
                />
              </div>
              <div className="form-group">
                <label>Accept-Language</label>
                <input
                  value={value.sourceHeaders?.['Accept-Language'] || ''}
                  onChange={(e) => updateSourceHeader('Accept-Language', e.target.value)}
                  className="form-input"
                  placeholder="zh-CN,zh;q=0.9"
                />
              </div>
              <div className="form-group">
                <label>Referer</label>
                <input
                  value={value.sourceHeaders?.Referer || ''}
                  onChange={(e) => updateSourceHeader('Referer', e.target.value)}
                  className="form-input"
                  placeholder={url || 'https://example.com/product'}
                />
              </div>
              <div className="form-group">
                <label>X-Requested-With</label>
                <input
                  value={value.sourceHeaders?.['X-Requested-With'] || ''}
                  onChange={(e) => updateSourceHeader('X-Requested-With', e.target.value)}
                  className="form-input"
                  placeholder="XMLHttpRequest"
                />
              </div>
            </div>
          </>
        )}

        <div className="form-group">
          <label>{value.sourceMode === 'api_json' ? '列表路径（兼容字段）' : '容器选择器'}</label>
          <input
            value={value.containerSelector}
            onChange={(e) => update('containerSelector', e.target.value)}
            className="form-input"
            placeholder="如 div.hap_infoBox"
          />
        </div>

        <div className="form-group">
          <label>{value.sourceMode === 'api_json' ? '条目表达式' : '列表项选择器（可选）'}</label>
          <input
            value={value.itemSelector}
            onChange={(e) => update('itemSelector', e.target.value)}
            className="form-input"
            placeholder="如 div.hap_infoOne"
          />
        </div>

        <div className="fields-section">
          <div className="fields-header">
            <span className="fields-title">提取字段</span>
            <button className="btn btn-sm btn-ghost" onClick={addField}>
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" width="14" height="14">
                <line x1="12" y1="5" x2="12" y2="19" />
                <line x1="5" y1="12" x2="19" y2="12" />
              </svg>
              添加字段
            </button>
          </div>

          <div className="fields-list">
            {value.fields.map((field, index) => (
              <div key={index} className="field-card">
                <div className="field-grid">
                  <div className="form-group">
                    <label>名称</label>
                    <input
                      value={field.name}
                      onChange={(e) => updateField(index, 'name', e.target.value)}
                      className="form-input"
                      placeholder="如 title"
                    />
                  </div>
                  <div className="form-group">
                    <label>{value.sourceMode === 'api_json' ? 'JSON 路径' : '选择器'}</label>
                    <input
                      value={field.selector}
                      onChange={(e) => updateField(index, 'selector', e.target.value)}
                      className="form-input"
                      placeholder="如 a.title"
                    />
                  </div>
                  <div className="form-group">
                    <label>类型</label>
                    <select value={field.type} onChange={(e) => updateField(index, 'type', e.target.value)} className="form-input">
                      <option value="text">文本 (text)</option>
                      <option value="attr">属性 (attr)</option>
                    </select>
                  </div>
                  {field.type === 'attr' && (
                    <div className="form-group">
                      <label>属性名</label>
                      <input
                        value={field.attr}
                        onChange={(e) => updateField(index, 'attr', e.target.value)}
                        className="form-input"
                        placeholder="默认 href"
                      />
                    </div>
                  )}
                  <div className="form-group">
                    <label>转换</label>
                    <input
                      value={field.transform}
                      onChange={(e) => updateField(index, 'transform', e.target.value)}
                      className="form-input"
                      placeholder="如 trim([])"
                    />
                  </div>
                </div>
                <button className="btn-icon btn-icon-danger field-remove-btn" title="删除字段" onClick={() => removeField(index)}>
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" width="16" height="16">
                    <line x1="18" y1="6" x2="6" y2="18" />
                    <line x1="6" y1="6" x2="18" y2="18" />
                  </svg>
                </button>
              </div>
            ))}
          </div>

          {value.fields.length === 0 && (
            <div className="empty">
              <p>暂无字段，点击上方按钮添加</p>
            </div>
          )}
        </div>
      </div>
    )
  }

  return (
    <div className="settings-section extraction-editor">
      <div className="ee-section-header">
        <h2>想关注什么内容？</h2>
      </div>

      <p className="section-desc">
        系统按「高级规则」页保存的扫描规则识别内容区域；未命中规则时，可在高级设置中手动配置并另存为规则。
      </p>

      <div className="scan-row">
        <div className="scan-action">
          <button className="btn btn-primary btn-sm" disabled={!url || scanning} onClick={handleScan}>
            {scanning ? '识别中...' : '按规则识别内容'}
          </button>
        </div>
      </div>

      {scanning && (
        <div className="loading">
          <div className="spinner" />
          <p>正在识别网页内容...</p>
        </div>
      )}

      {!scanning && scanResult && scanResult.containers && scanResult.containers.length > 0 && (
        <div className="scan-results">
          <p className="results-label">
            命中 {scanResult.containers.length} 条扫描规则，找到以下内容区域，请选择最符合的一项：
          </p>
          {scanResult.containers.map((container, ci) => (
            <div
              key={ci}
              className={`candidate-card${selectedIndex === ci ? ' selected' : ''}`}
              onClick={() => setSelectedIndex(ci)}
            >
              <div className="candidate-header">
                <div className="candidate-info">
                  <span className="candidate-badge">{container.strategy || `内容区域 ${ci + 1}`}</span>
                  <span className="candidate-count">发现 {container.item_count} 条内容</span>
                </div>
                <button
                  className="btn btn-sm btn-primary apply-btn"
                  type="button"
                  onClick={(e) => {
                    e.stopPropagation()
                    applyCandidate(container)
                  }}
                >
                  选择此区域
                </button>
              </div>
              <div className="candidate-samples">
                {(container.sample_items || []).slice(0, 5).map((item, ii) => (
                  <div key={ii} className="sample-item">
                    <span className="sample-title">{item.title || '未命名条目'}</span>
                    {item.date ? <span className="sample-meta">{item.date}</span> : null}
                  </div>
                ))}
                {container.item_count > 5 && <div className="sample-more">...还有 {container.item_count - 5} 条</div>}
              </div>
            </div>
          ))}
        </div>
      )}

      {!scanning && !scanResult?.containers?.length && scanned && (
        <div className="empty-scan">
          <p>该网址未命中任何已保存的扫描规则。请先在「高级规则」页创建规则，或在高级设置中手动配置。</p>
        </div>
      )}

      {scanError && <div className="form-error">{scanError}</div>}

      {value.containerSelector && (
        <div className="selection-confirmed">
          <div className="confirmed-content">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" width="14" height="14">
              <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />
              <polyline points="22 4 12 14.01 9 11.01" />
            </svg>
            <span>已识别内容区域，系统将监控新出现的内容</span>
          </div>
        </div>
      )}
    </div>
  )
}

// frontend/src/components/monitor/form/ExtractionEditor.vue
<template>
  <div :class="advanced ? 'advanced-panel-section' : 'settings-section'">
    <template v-if="!advanced">
    <div class="section-header">
      <h2>想关注什么内容？</h2>
    </div>

    <p class="section-desc">关键词可以留空，系统会自动识别网页中的主要内容列表。</p>

    <div class="scan-row">
      <div class="form-group scan-keyword">
        <label>关注的关键词 <span class="optional-label">可选</span></label>
        <input v-model="keyword" class="form-input" placeholder="例如：公告、录用、开售" @keyup.enter="handleScan" />
      </div>
      <div class="scan-action">
        <button class="btn btn-primary btn-sm" :disabled="!url || scanning" @click="handleScan">
          {{ scanning ? '识别中...' : '自动识别内容' }}
        </button>
      </div>
    </div>

    <div class="loading" v-if="scanning"><div class="spinner" /><p>正在识别网页内容...</p></div>

    <div class="scan-results" v-else-if="scanResult && scanResult.containers && scanResult.containers.length > 0">
      <p class="results-label">找到了 {{ scanResult.containers.length }} 个可能的内容区域，请选择最符合的一项：</p>
      <div
        v-for="(container, ci) in scanResult.containers"
        :key="ci"
        class="candidate-card"
        :class="{ selected: selectedIndex === ci }"
        @click="selectedIndex = ci"
      >
        <div class="candidate-header">
          <div class="candidate-info">
            <span class="candidate-badge">内容区域 {{ ci + 1 }}</span>
            <span class="candidate-count">发现 {{ container.item_count }} 条内容</span>
            <span class="candidate-hit" v-if="container.keyword_hits">{{ container.keyword_hits }} 条与关键词相关</span>
          </div>
          <button class="btn btn-sm btn-primary apply-btn" type="button" @click.stop="applyCandidate(container)">选择此区域</button>
        </div>
        <div class="candidate-samples">
          <div v-for="(item, ii) in (container.sample_items || []).slice(0, 5)" :key="ii" class="sample-item">
            <span class="sample-title">{{ item.title || item.sku || '未命名条目' }}</span>
            <span class="sample-meta" v-if="item.price">{{ item.price }}</span>
            <span class="sample-meta" v-else-if="item.date">{{ item.date }}</span>
          </div>
          <div class="sample-more" v-if="container.item_count > 5">...还有 {{ container.item_count - 5 }} 条</div>
        </div>
      </div>
    </div>

    <div class="empty-scan" v-else-if="scanned">
      <p>暂时没有识别到合适的内容。可以换个关键词重试，或在高级设置中手动配置。</p>
    </div>

    <div class="form-error" v-if="scanError">{{ scanError }}</div>

    <div v-if="modelValue.containerSelector" class="selection-confirmed">
      <div class="confirmed-content">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" width="14" height="14"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><polyline points="22 4 12 14.01 9 11.01"/></svg>
        <span>已识别内容区域，系统将监控新出现的内容</span>
      </div>
    </div>
    </template>

    <div class="manual-section" v-else>
      <h3>网页提取规则</h3>
      <p class="advanced-section-desc">仅在自动识别不准确时修改这些技术选项。</p>
      <div class="form-group">
        <label>数据源</label>
        <select :value="modelValue.sourceMode || 'html'" @change="updateSourceMode($event.target.value)" class="form-input">
          <option value="html">网页 HTML</option>
          <option value="api_json">公开 JSON API</option>
        </select>
      </div>

      <template v-if="modelValue.sourceMode === 'api_json'">
        <div class="source-grid">
          <div class="form-group source-url">
            <label>JSON API URL</label>
            <input :value="modelValue.sourceUrl" @input="update('sourceUrl', $event.target.value)" class="form-input" placeholder="https://example.com/api/products" />
          </div>
          <div class="form-group">
            <label>列表路径</label>
            <input :value="modelValue.itemsPath" @input="update('itemsPath', $event.target.value)" class="form-input" placeholder="data.items" />
          </div>
          <div class="form-group">
            <label>过滤字段（可选）</label>
            <input :value="modelValue.filterPath" @input="update('filterPath', $event.target.value)" class="form-input" placeholder="is_selling" />
          </div>
          <div class="form-group">
            <label>过滤值</label>
            <input :value="modelValue.filterEquals" @input="update('filterEquals', $event.target.value)" class="form-input" placeholder="true" />
          </div>
        </div>
        <div class="header-grid">
          <div class="form-group">
            <label>Accept</label>
            <input :value="modelValue.sourceHeaders?.Accept || ''" @input="updateSourceHeader('Accept', $event.target.value)" class="form-input" placeholder="application/json" />
          </div>
          <div class="form-group">
            <label>Accept-Language</label>
            <input :value="modelValue.sourceHeaders?.['Accept-Language'] || ''" @input="updateSourceHeader('Accept-Language', $event.target.value)" class="form-input" placeholder="zh-CN,zh;q=0.9" />
          </div>
          <div class="form-group">
            <label>Referer</label>
            <input :value="modelValue.sourceHeaders?.Referer || ''" @input="updateSourceHeader('Referer', $event.target.value)" class="form-input" :placeholder="url || 'https://example.com/product'" />
          </div>
          <div class="form-group">
            <label>X-Requested-With</label>
            <input :value="modelValue.sourceHeaders?.['X-Requested-With'] || ''" @input="updateSourceHeader('X-Requested-With', $event.target.value)" class="form-input" placeholder="XMLHttpRequest" />
          </div>
        </div>
      </template>

      <div class="form-group">
        <label>{{ modelValue.sourceMode === 'api_json' ? '列表路径（兼容字段）' : '容器选择器' }}</label>
        <input :value="modelValue.containerSelector" @input="update('containerSelector', $event.target.value)" class="form-input" placeholder="如 div.hap_infoBox" />
      </div>

      <div class="form-group">
        <label>{{ modelValue.sourceMode === 'api_json' ? '条目表达式' : '列表项选择器（可选）' }}</label>
        <input :value="modelValue.itemSelector" @input="update('itemSelector', $event.target.value)" class="form-input" placeholder="如 div.hap_infoOne" />
      </div>

      <div class="fields-section">
        <div class="fields-header">
          <span class="fields-title">提取字段</span>
          <button class="btn btn-sm btn-ghost" @click="addField">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" width="14" height="14"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg>
            添加字段
          </button>
        </div>

        <div class="fields-list">
          <div v-for="(field, index) in modelValue.fields" :key="index" class="field-card">
            <div class="field-grid">
              <div class="form-group">
                <label>名称</label>
                <input :value="field.name" @input="updateField(index, 'name', $event.target.value)" class="form-input" placeholder="如 title" />
              </div>
              <div class="form-group">
                <label>{{ modelValue.sourceMode === 'api_json' ? 'JSON 路径' : '选择器' }}</label>
                <input :value="field.selector" @input="updateField(index, 'selector', $event.target.value)" class="form-input" placeholder="如 a.title" />
              </div>
              <div class="form-group">
                <label>类型</label>
                <select :value="field.type" @change="updateField(index, 'type', $event.target.value)" class="form-input">
                  <option value="text">文本 (text)</option>
                  <option value="attr">属性 (attr)</option>
                </select>
              </div>
              <div class="form-group" v-if="field.type === 'attr'">
                <label>属性名</label>
                <input :value="field.attr" @input="updateField(index, 'attr', $event.target.value)" class="form-input" placeholder="默认 href" />
              </div>
              <div class="form-group">
                <label>转换</label>
                <input :value="field.transform" @input="updateField(index, 'transform', $event.target.value)" class="form-input" placeholder="如 trim([])" />
              </div>
            </div>
            <button class="field-remove-btn" title="删除字段" @click="removeField(index)">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" width="16" height="16"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>
            </button>
          </div>
        </div>

        <div class="empty" v-if="modelValue.fields.length === 0">
          <p>暂无字段，点击上方按钮添加</p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed } from 'vue'
import { previewScan } from '../../../api/monitors'

const props = defineProps({
  modelValue: { type: Object, required: true },
  url: { type: String, default: '' },
  advanced: { type: Boolean, default: false },
})
const emit = defineEmits(['update:modelValue'])

const keyword = ref('')
const scanning = ref(false)
const scanResult = ref(null)
const scanned = ref(false)
const scanError = ref(null)
const selectedIndex = ref(null)

function strategyLabel(strategy) {
  if (!strategy) return ''
  if (strategy.startsWith('template_')) return `规则「${strategy.slice(9)}」`
  const labels = {
    keyword_ancestor: '关键词定位',
    repeated_list: '重复列表',
    link_cluster: '链接簇',
    table_rows: '表格检测',
  }
  return labels[strategy] || strategy
}

function strategyClass(strategy) {
  return strategy?.startsWith('template_') || strategy?.startsWith('rule_') ? 'strategy-rule' : 'strategy-heuristic'
}

const keywordPlaceholder = computed(() => '公告,通知,公示')

async function handleScan() {
  if (!props.url) return
  scanning.value = true
  scanned.value = false
  scanError.value = null
  selectedIndex.value = null
  try {
    const res = await previewScan({
      url: props.url.trim(),
      keywords: keyword.value || keywordPlaceholder.value,
      strategy_type: 'presence',
    })
    if (res.code === 0 && res.data) {
      scanResult.value = res.data
      if (res.data.containers?.length === 1) {
        applyCandidate(res.data.containers[0])
        scanning.value = false
        return
      }
    } else {
      scanError.value = res.message || '扫描失败'
    }
  } catch (e) {
    scanError.value = e.response?.data?.message || e.message || '扫描失败'
  }
  scanned.value = true
  scanning.value = false
}

function applyCandidate(container) {
  const config = container.config || {}
  const fields = (config.fields || []).map(f => ({
    name: f.name || '', selector: f.selector || '', type: f.type || 'text', attr: f.attr || '', transform: f.transform || '',
  }))
  const extracted = {
    ...props.modelValue,
    containerSelector: config.container || container.container_css || '',
    itemSelector: config.item || container.item_css || '',
  }
  if (config.fetch_config) {
    extracted.sourceMode = config.fetch_config.mode || 'html'
    extracted.sourceUrl = config.fetch_config.url || ''
    extracted.itemsPath = config.fetch_config.items_path || ''
    extracted.filterPath = config.fetch_config.filter_path || ''
    extracted.filterEquals = config.fetch_config.filter_equals ?? ''
    extracted.sourceHeaders = config.fetch_config.headers || {}
  } else {
    extracted.sourceMode = 'html'
    extracted.sourceUrl = ''
    extracted.itemsPath = ''
    extracted.filterPath = ''
    extracted.filterEquals = ''
    extracted.sourceHeaders = {}
  }
  if (fields.length > 0) extracted.fields = fields
  emit('update:modelValue', extracted)
  scanned.value = false
  scanResult.value = null
}

function update(key, value) {
  emit('update:modelValue', { ...props.modelValue, [key]: value })
}

function updateSourceMode(mode) {
  const next = { ...props.modelValue, sourceMode: mode }
  if (mode === 'html') {
    next.sourceUrl = ''
    next.itemsPath = ''
    next.filterPath = ''
    next.filterEquals = ''
    next.sourceHeaders = {}
  }
  emit('update:modelValue', next)
}

function updateSourceHeader(name, value) {
  const headers = { ...(props.modelValue.sourceHeaders || {}) }
  if (value.trim()) headers[name] = value
  else delete headers[name]
  emit('update:modelValue', { ...props.modelValue, sourceHeaders: headers })
}

function updateField(index, key, value) {
  const fields = [...props.modelValue.fields]
  fields[index] = { ...fields[index], [key]: value }
  emit('update:modelValue', { ...props.modelValue, fields })
}

function addField() {
  const fields = [...props.modelValue.fields, { name: '', selector: '', type: 'text', attr: '', transform: '' }]
  emit('update:modelValue', { ...props.modelValue, fields })
}

function removeField(index) {
  const fields = [...props.modelValue.fields]
  fields.splice(index, 1)
  emit('update:modelValue', { ...props.modelValue, fields })
}
</script>

<style scoped>
.section-header { margin-bottom: 0.5rem; }
.section-desc { font-size: 0.8125rem; color: var(--text-secondary); margin-bottom: 1rem; }
.optional-label { color: var(--text-muted); font-size: 0.6875rem; font-weight: 500; text-transform: none; }
.advanced-panel-section h3 { margin-bottom: 0.2rem; color: var(--text); font-size: 0.875rem; }
.advanced-section-desc { margin-bottom: 1rem; color: var(--text-muted); font-size: 0.75rem; }
.selection-confirmed { margin-top: 0.75rem; padding: 0.65rem 0.75rem; border-left: 3px solid var(--success); background: var(--success-bg); color: var(--success); font-size: 0.8125rem; font-weight: 700; }

.scan-row {
  display: flex;
  align-items: flex-end;
  gap: 0.75rem;
  margin-bottom: 1rem;
}
.scan-keyword { flex: 1; margin-bottom: 0; }
.scan-action { flex-shrink: 0; padding-bottom: 2px; }

.scan-results { margin-bottom: 1rem; }
.results-label { font-size: 0.8125rem; color: var(--text-secondary); margin-bottom: 0.5rem; }

.candidate-card {
  background: var(--bg-card);
  border: 2px solid transparent;
  border-radius: var(--radius-lg);
  padding: 0.85rem;
  margin-bottom: 0.5rem;
  cursor: pointer;
  transition: var(--transition);
}
.candidate-card:hover { background: var(--bg-hover); }
.candidate-card.selected { border-color: var(--green); background: rgba(29, 185, 84, 0.04); }

.candidate-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.4rem; }
.candidate-info { display: flex; align-items: center; gap: 0.5rem; }
.candidate-badge { font-size: 0.6875rem; font-weight: 700; color: var(--text); background: var(--bg-elevated); padding: 0.15rem 0.5rem; border-radius: var(--radius-pill); }
.candidate-count { font-size: 0.75rem; color: var(--text-secondary); }
.candidate-hit { font-size: 0.75rem; color: var(--green); }
.candidate-strategy { font-size: 0.6875rem; padding: 0.1rem 0.5rem; border-radius: var(--radius-pill); white-space: nowrap; }
.candidate-strategy.strategy-rule { color: #fff; background: #e74c3c; font-weight: 700; }
.candidate-strategy.strategy-heuristic { color: var(--accent); background: var(--bg-elevated); }
.apply-btn { flex-shrink: 0; }

.candidate-selector { margin-bottom: 0.5rem; font-size: 0.75rem; color: var(--text-muted); }
.candidate-selector code { color: var(--green); }
.selector-sep { color: var(--text-muted); }

.candidate-samples { display: flex; flex-direction: column; gap: 0.15rem; }
.sample-item { display: flex; justify-content: space-between; padding: 0.25rem 0.5rem; border-radius: 4px; background: var(--bg-elevated); font-size: 0.8125rem; }
.sample-title { color: var(--text); flex: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.sample-meta { color: var(--text-muted); font-size: 0.75rem; margin-left: 0.5rem; flex-shrink: 0; }
.sample-more { font-size: 0.75rem; color: var(--text-muted); text-align: center; padding: 0.2rem; }

.empty-scan { text-align: center; padding: 1.5rem; color: var(--text-secondary); font-size: 0.8125rem; }

.divider { height: 1px; background: var(--border-light); margin: 1.25rem 0; }

.advanced-toggle {
  display: inline-flex; align-items: center; gap: 0.35rem;
  cursor: pointer; font-size: 0.75rem; font-weight: 700; color: var(--text-secondary);
  margin-bottom: 0.75rem;
  user-select: none; transition: var(--transition);
}
.advanced-toggle:hover { color: var(--text); }
.advanced-toggle svg { transition: transform 0.2s; }
.advanced-toggle svg.rotated { transform: rotate(90deg); }

.manual-section { margin-top: 0.75rem; }
.source-grid { display: grid; grid-template-columns: minmax(0, 2fr) repeat(3, minmax(0, 1fr)); gap: 0.5rem; }
.source-grid .form-group { min-width: 0; }
.header-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 0.5rem; }
.header-grid .form-group { min-width: 0; }

.fields-section { margin-top: 0.5rem; }
.fields-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.75rem; }
.fields-title { font-size: 0.75rem; font-weight: 700; color: var(--text-secondary); }
.fields-list { display: flex; flex-direction: column; gap: 0.5rem; }
.field-card { display: flex; gap: 0.5rem; align-items: flex-start; padding: 0.75rem; background: var(--bg-surface); border-radius: var(--radius-lg); }
.field-grid { flex: 1; display: grid; grid-template-columns: 1fr 1fr 1fr 1fr 1fr; gap: 0.5rem; }
.field-remove-btn {
  background: none; border: none; cursor: pointer; padding: 0.4rem;
  border-radius: var(--radius-circle); transition: var(--transition); color: var(--text-muted);
  display: inline-flex; align-items: center; flex-shrink: 0; margin-top: 1.5rem;
}
.field-remove-btn:hover { background: var(--error-bg); color: var(--error); }

@media (max-width: 768px) {
  .scan-row { flex-direction: column; align-items: stretch; }
  .field-grid { grid-template-columns: 1fr 1fr; }
  .source-grid, .header-grid { grid-template-columns: 1fr; }
}
</style>
