// frontend/src/components/UpdatePanel.vue
<template>
  <div class="update-panel">
    <button class="version-btn" :disabled="checking || state === 'downloading' || state === 'restarting'" @click="handleClick">
      <span v-if="state === 'idle'">{{ version }}</span>
      <span v-else-if="state === 'checking'">检查中...</span>
      <span v-else-if="state === 'uptodate'">已是最新</span>
      <span v-else-if="state === 'error'">检查失败</span>
      <span v-else-if="state === 'downloading'">下载更新中...</span>
      <span v-else-if="state === 'restarting'">即将重启...</span>
      <span v-else-if="state === 'failed'">{{ errorMsg || '更新失败' }}</span>
    </button>

    <div class="update-actions" v-if="state === 'available'">
      <button class="update-btn" @click="handleUpdate">升级到 {{ latestVersion }}</button>
    </div>
    <div class="update-actions" v-if="state === 'downloading'">
      <div class="progress-bar"><div class="progress-fill fill-anim" /></div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted, onUnmounted } from 'vue'
import { fetchVersion, checkUpdate, applyUpdate, fetchUpdateStatus } from '../api/monitors'

const version = ref('')
const state = ref('idle')
const latestVersion = ref('')
const downloadURL = ref('')
const errorMsg = ref('')
let statusTimer = null

onMounted(async () => {
  try {
    const res = await fetchVersion()
    if (res.code === 0 && res.data) {
      version.value = res.data.version
    }
  } catch {}
})

onUnmounted(() => {
  if (statusTimer) clearInterval(statusTimer)
})

async function handleClick() {
  state.value = 'checking'
  try {
    const res = await checkUpdate()
    if (res.code === 0 && res.data) {
      if (res.data.has_update) {
        latestVersion.value = res.data.latest_version
        downloadURL.value = res.data.download_url
        state.value = 'available'
      } else {
        state.value = 'uptodate'
        setTimeout(() => { state.value = 'idle' }, 2000)
      }
    } else {
      state.value = 'error'
      setTimeout(() => { state.value = 'idle' }, 2000)
    }
  } catch {
    state.value = 'error'
    setTimeout(() => { state.value = 'idle' }, 2000)
  }
}

async function handleUpdate() {
  if (!downloadURL.value) return
  state.value = 'downloading'
  try {
    await applyUpdate()
    pollStatus()
  } catch {
    state.value = 'failed'
    errorMsg.value = '请求失败'
    setTimeout(() => { state.value = 'idle' }, 3000)
  }
}

function pollStatus() {
  statusTimer = setInterval(async () => {
    try {
      const res = await fetchUpdateStatus()
      if (res.code === 0 && res.data) {
        if (res.data.status === 'done') {
          state.value = 'restarting'
          clearInterval(statusTimer)
        } else if (res.data.status === 'error') {
          errorMsg.value = res.data.message || '更新失败'
          state.value = 'failed'
          clearInterval(statusTimer)
          setTimeout(() => { state.value = 'idle' }, 5000)
        }
      }
    } catch {
      state.value = 'restarting'
      clearInterval(statusTimer)
    }
  }, 2000)
}
</script>

<style scoped>
.update-panel {
  border-top: 1px solid var(--border-light);
  padding: 0.5rem;
  display: flex;
  flex-direction: column;
  gap: 0.4rem;
}

.version-btn {
  width: 100%;
  padding: 0.4rem;
  border: none;
  border-radius: var(--radius);
  background: var(--bg-elevated);
  color: var(--text-muted);
  font-size: 0.6875rem;
  font-weight: 600;
  cursor: pointer;
  transition: var(--transition);
  text-align: center;
}
.version-btn:hover { color: var(--text); background: var(--bg-hover); }
.version-btn:disabled { opacity: 0.7; cursor: default; }

.update-btn {
  width: 100%;
  padding: 0.4rem;
  border: none;
  border-radius: var(--radius);
  background: var(--green);
  color: #000;
  font-size: 0.75rem;
  font-weight: 700;
  cursor: pointer;
  transition: var(--transition);
}
.update-btn:hover { opacity: 0.9; }
.update-btn:disabled { opacity: 0.5; cursor: not-allowed; }

.progress-bar {
  height: 3px;
  background: var(--bg-elevated);
  border-radius: 2px;
  overflow: hidden;
  margin-top: 0.25rem;
}
.progress-fill {
  height: 100%;
  background: var(--green);
  border-radius: 2px;
}
.fill-anim {
  width: 60%;
  animation: progress-indeterminate 1.5s ease-in-out infinite;
}
@keyframes progress-indeterminate {
  0% { transform: translateX(-100%); }
  100% { transform: translateX(200%); }
}
</style>

// frontend/src/components/UpdatePanel.tsx
import { useEffect, useRef, useState } from 'react'
import { fetchVersion, checkUpdate, applyUpdate, fetchUpdateStatus } from '../api/monitors'
import './UpdatePanel.css'

type PanelState = 'idle' | 'checking' | 'available' | 'uptodate' | 'error' | 'downloading' | 'restarting' | 'failed'

// 重启等待上限：150 × 2s ≈ 5 分钟，超时放弃并回到 idle
const RESTART_POLL_LIMIT = 150

export default function UpdatePanel() {
  const [version, setVersion] = useState('')
  const [state, setState] = useState<PanelState>('idle')
  const [latestVersion, setLatestVersion] = useState('')
  const [errorMsg, setErrorMsg] = useState('')
  const statusTimer = useRef<ReturnType<typeof setInterval> | null>(null)
  const delayedTimers = useRef<ReturnType<typeof setTimeout>[]>([])
  const downloadURL = useRef('')

  const later = (fn: () => void, ms: number) => {
    delayedTimers.current.push(setTimeout(fn, ms))
  }

  const stopPolling = () => {
    if (statusTimer.current) {
      clearInterval(statusTimer.current)
      statusTimer.current = null
    }
  }

  useEffect(() => {
    let cancelled = false
    fetchVersion()
      .then((res) => {
        if (!cancelled && res.code === 0 && res.data) setVersion(res.data.version)
      })
      .catch(() => {})
    return () => {
      cancelled = true
      stopPolling()
      for (const t of delayedTimers.current) clearTimeout(t)
      delayedTimers.current = []
    }
  }, [])

  async function handleClick() {
    setState('checking')
    try {
      const res = await checkUpdate()
      if (res.code === 0 && res.data) {
        if (res.data.has_update) {
          setLatestVersion(res.data.latest_version)
          downloadURL.current = res.data.download_url
          setState('available')
        } else {
          setState('uptodate')
          later(() => setState('idle'), 2000)
        }
      } else {
        setState('error')
        later(() => setState('idle'), 2000)
      }
    } catch {
      setState('error')
      later(() => setState('idle'), 2000)
    }
  }

  async function handleUpdate() {
    if (!downloadURL.current) return
    setState('downloading')
    try {
      await applyUpdate()
      pollStatus()
    } catch {
      setState('failed')
      setErrorMsg('请求失败')
      later(() => setState('idle'), 3000)
    }
  }

  function pollStatus() {
    // 阶段一：轮询 /update/status 直到 done/error；
    // 阶段二（waitingRestart）：服务正在重启，改为探测版本接口，
    // 确认经历过一次不可达（restartConfirmed）且重新可达后，刷新版本号并回到 idle。
    let waitingRestart = false
    let restartConfirmed = false
    let ticks = 0
    stopPolling()
    statusTimer.current = setInterval(async () => {
      ticks++
      if (ticks > RESTART_POLL_LIMIT) {
        stopPolling()
        setState('idle')
        return
      }
      try {
        if (!waitingRestart) {
          const res = await fetchUpdateStatus()
          if (res.code !== 0 || !res.data) return
          if (res.data.status === 'done') {
            waitingRestart = true
            setState('restarting')
          } else if (res.data.status === 'error') {
            setErrorMsg(res.data.message || '更新失败')
            setState('failed')
            stopPolling()
            later(() => setState('idle'), 5000)
          }
          // 其余状态（下载中等）继续轮询
        } else {
          const v = await fetchVersion()
          if (v.code === 0 && v.data?.version) {
            // 老进程可能尚未退出；超过约 1 分钟仍可达则视为原地热更新成功
            if (restartConfirmed || ticks > 30) {
              stopPolling()
              setVersion(v.data.version)
              setState('idle')
            }
          } else {
            restartConfirmed = true
          }
        }
      } catch {
        if (!waitingRestart) {
          // 更新过程中服务不可达：视为正在重启，转入阶段二继续等待恢复
          waitingRestart = true
          setState('restarting')
        } else {
          restartConfirmed = true
        }
      }
    }, 2000)
  }

  return (
    <div className="update-panel">
      <button
        className="version-btn"
        disabled={state === 'checking' || state === 'downloading' || state === 'restarting'}
        onClick={handleClick}
      >
        {state === 'idle' && <span>{version}</span>}
        {state === 'checking' && <span>检查中...</span>}
        {state === 'uptodate' && <span>已是最新</span>}
        {state === 'error' && <span>检查失败</span>}
        {state === 'downloading' && <span>下载更新中...</span>}
        {state === 'restarting' && <span>即将重启...</span>}
        {state === 'failed' && <span>{errorMsg || '更新失败'}</span>}
      </button>

      {state === 'available' && (
        <div className="update-actions">
          <button className="update-btn" onClick={handleUpdate}>
            升级到 {latestVersion}
          </button>
        </div>
      )}
      {state === 'downloading' && (
        <div className="update-actions">
          <div className="progress-bar">
            <div className="progress-fill fill-anim" />
          </div>
        </div>
      )}
    </div>
  )
}
